version: "3"

services:
  rng:
    build: .
    depends_on:
     - mongo
    command: tail -f /dev/null
    environment:
      - MONGO_HOST=mongo
    volumes:
      - ./:/app

  mongo:
    image: mongo
